plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  'sass-loader@*':
    optionalDependencies:
      node-sass: '*'
  'gatsby@*':
    optionalDependencies:
      '@babel/types': '*'
  'gatsby-core-utils@*':
    optionalDependencies:
      typescript: '*'
  'gatsby-cli@*':
    optionalDependencies:
      typescript: '*'
#  'tsutils@*':
#    peerDependencies:
#      typescript: '*'
#  '@typescript-eslint/typescript-estree@*':
#    peerDependencies:
#      typescript: '*'
#  '@typescript-eslint/eslint-plugin@*':
#    peerDependencies:
#      typescript: '*'
