plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  'sass-loader@*':
    optionalDependencies:
      node-sass: '*'
  'gatsby@*':
    optionalDependencies:
      '@babel/types': '*'
  'gatsby-core-utils@*':
    optionalDependencies:
      typescript: '*'
  'gatsby-plugin-google-fonts-v2@*':
    dependencies:
      typescript: '*'
  'gatsby-plugin-robots-txt@*':
    dependencies:
      prettier: '*'
  'gatsby-source-contentful@*':
    dependencies:
      progress: '*'
  framer-motion@*:
    optionalDependencies:
      csstype: "*"
    