packageExtensions:
  framer-motion@*:
    optionalDependencies:
      csstype: "*"
  gatsby-core-utils@*:
    optionalDependencies:
      typescript: "*"
  gatsby-plugin-google-fonts-v2@*:
    dependencies:
      typescript: "*"
  gatsby-plugin-robots-txt@*:
    dependencies:
      prettier: "*"
  gatsby-recipes@*:
    dependencies:
      "@mdx-js/mdx": "*"
  gatsby-source-contentful@*:
    dependencies:
      progress: "*"
  gatsby@*:
    optionalDependencies:
      "@babel/types": "*"
  sass-loader@*:
    optionalDependencies:
      node-sass: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
