---
overwrite: true
generates:
  schemas/gql-contentful-schema.json:
    schema:
      - https://graphql.contentful.com/content/v1/spaces/${CONTENTFUL_SPACE_ID}/environments/master:
          headers:
            Authorization: Bearer ${CONTENTFUL_ACCESS_TOKEN}
    plugins:
      - introspection
